######################################################################
# Automatically generated by qmake (3.0) czw. gru 29 14:15:05 2016
######################################################################

TEMPLATE = app
TARGET = SR_srv_semaforow
INCLUDEPATH += .
LIBS += -lboost_program_options
# Input
SOURCES += main.cpp \
    client.cpp

HEADERS += \
    client.hpp
